name: ccp_puno_flutter
description: Aplicaciond para el CCP-Puno
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.1.1
  flutter_riverpod: ^2.3.2
  go_router: ^6.5.2
  google_fonts: ^4.0.3
  flutter_dotenv: ^5.0.2
  formz: ^0.6.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
